name: Build Vue
on:
  push:
    branches:
      - release
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'SgkSchedule'
        reponame: 'web_v2'
        token: ${{ secrets.GITHUB_TOKEN }}
        useyarn: true